### ISSUE TITLE
有纯前端版本吗？

### ISSUE THREAD

**Issue by DSYZayn** [1939323749/webdesign-frontend#1]
# 能否提供纯前端版本
## 首屏加载需要后端服务，是否能去除校验，分离出纯前端版本?

**Comment by 1939323749** [comment]
项目中首屏加载并非校验,而是向后端获取数据,在加载数据后再进行页面渲染,此项目配合[webdesign-backend](https://github.com/1939323749/webdesign-backend)进行演示,api设计在[routers](https://github.com/1939323749/webdesign-backend/blob/main/router/routers.go),首页的获取的数据为json格式,可能的参考:
```json
[
    {
        "bvid": "BV1No4y1G7t3",
        "category": "知识",
        "description": "亚洲最年轻的国家在哪里？【奇葩小国47】",
        "id": 25,
        "rating": 5,
        "ratingCount": 1,
        "time": "2023-05-21T08:29:57.753+08:00",
        "url": "http://i2.hdslb.com/bfs/archive/94a09ed9362ad419270f4d6ae06a43b7a6055f8b.jpg",
        "vote": null
    },
    {
        "bvid": "BV11i4y1L7QQ",
        "category": "知识",
        "description": "苏联为何而强大？【小约翰】",
        "id": 26,
        "rating": 5,
        "ratingCount": 1,
        "time": "2023-05-21T08:30:35.617+08:00",
        "url": "http://i0.hdslb.com/bfs/archive/c9f57cdf65d7f79c32b5233f9f3b9d01e302f907.jpg",
        "vote": null
    },
]
```
其中`url`为视频封面,`bvid`为b站视频的bv号,`rating`和`ratingCount`分别为评分和评分人数
演示图片:
<img width="1039" alt="截屏2023-06-25 22 44 45" src="https://github.com/1939323749/webdesign-frontend/assets/28222273/74385ccc-2291-46f7-b738-0350a323b979">
由于本人正在准备期末考试,纯前端版本可能在后续提供,感谢您的关注!

**Comment by DSYZayn** [comment]
#版本请求
收到，谢谢回复！
